controllers/GroupController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Group;
use app\models\GroupSearch;
use app\models\User;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\ForbiddenHttpException;

/**
 * GroupController implements the CRUD actions for Group model.
 */
class GroupController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Group models.
     * @return mixed
     */
    public function actionIndex() {
        if (Yii::$app->user->isGuest || !\Yii::$app->user->identity->is('admin')) {
            throw new ForbiddenHttpException('Access denied');
        }
        $searchModel = new GroupSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all Group models.
     * @return mixed
     */
    public function actionTeacherindex() {

        if (Yii::$app->user->isGuest || !\Yii::$app->user->identity->is('teacher')) {
            throw new ForbiddenHttpException('Access denied');
        }
        $searchModel = new GroupSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $dataProvider->query->andFilterWhere([
            'creatorId' => \Yii::$app->user->identity->userId
        ]);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Group model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id) {
	if(Yii::$app->user->isGuest){
            throw new ForbiddenHttpException('Access denied');
	}
        if (!\Yii::$app->user->identity->is('admin') && !\Yii::$app->user->identity->is('teacher')) {
            throw new ForbiddenHttpException('Access denied');
        }

        $model = $this->findModel($id);

        if (\Yii::$app->user->identity->is('teacher') && \Yii::$app->user->identity->userId != $model->creatorId) {
            throw new ForbiddenHttpException('Access denied');
        }

        $users = $model->getUsers()->orderBy('userLastName')->asArray()->all();

        $query = new \yii\db\Query;
        $query->from(['disk' => '{{%disk}}', 'groupaccess' => '{{%groupaccess}}'])
                ->where('disk.diskId=groupaccess.diskId and groupaccess.groupId=' . ( (int) $model->groupId ))
                ->orderBy('disk.diskTitle');
        $disks = $query->all();

        return $this->render('view', [
                    'model' => $model,
                    'users' => $users,
                    'disks' => $disks,
        ]);
    }

    /**
     * Creates a new Group model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {

	if(Yii::$app->user->isGuest){
            throw new ForbiddenHttpException('Access denied');
	}
        if (!\Yii::$app->user->identity->is('admin') && !\Yii::$app->user->identity->is('teacher')) {
            throw new ForbiddenHttpException('Access denied');
        }

        $model = new Group();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            $model->creatorId = \Yii::$app->user->identity->userId;
            $model->save();

            return $this->redirect(['view', 'id' => $model->groupId]);
        } else {
            return $this->render('create', ['model' => $model,]);
        }
    }

    /**
     * Updates an existing Group model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id) {

	if(Yii::$app->user->isGuest){
            throw new ForbiddenHttpException('Access denied');
	}
        if (!\Yii::$app->user->identity->is('admin') && !\Yii::$app->user->identity->is('teacher')) {
            throw new ForbiddenHttpException('Access denied');
        }

        $model = $this->findModel($id);

        if (\Yii::$app->user->identity->is('teacher') && \Yii::$app->user->identity->userId != $model->creatorId) {
            throw new ForbiddenHttpException('Access denied');
        }



        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['update', 'id' => $model->groupId]);
        } else {

            $query = new \yii\db\Query;
            $query->from(['disk' => '{{%disk}}'])
                    ->orderBy('disk.diskTitle');
            $disks = $query->all();

            $userQuery = User::find()->orderBy('userLastName');
            if (\Yii::$app->user->identity->is('teacher')) {
                $userQuery->andFilterWhere(['creatorId' => \Yii::$app->user->identity->userId]);
            }
            // echo "****************";
            // print_r($userQuery->prepare(Yii::$app->db->queryBuilder)->createCommand()->rawSql);
            $users = $userQuery->asArray()->all();
            for ($cnt = count($users), $i = 0; $i < $cnt; $i++) {
                $users[$i]['userFullName'] = " {$users[$i]['userLastName']} {$users[$i]['userFirstName']} {$users[$i]['userLogin']}  ";
                $users[$i]['userPassword'] = '';
            }

            return $this->render('update', [
                        'model' => $model,
                        'disks' => $disks,
                        'students' => $users
            ]);
        }
    }

    /**
     * Deletes an existing Group model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id) {

	if(Yii::$app->user->isGuest){
            throw new ForbiddenHttpException('Access denied');
	}
        if (!\Yii::$app->user->identity->is('admin') && !\Yii::$app->user->identity->is('teacher')) {
            throw new ForbiddenHttpException('Access denied');
        }
        $model = $this->findModel($id);

        if (\Yii::$app->user->identity->is('teacher') && \Yii::$app->user->identity->userId != $model->creatorId) {
            throw new ForbiddenHttpException('Access denied');
        }

        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Group model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Group the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Group::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\UserSearch;
use app\models\LoginForm;
use app\models\UserBatchForm;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\ForbiddenHttpException;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex() {
        if (Yii::$app->user->isGuest || !\Yii::$app->user->identity->is('admin')) {
            throw new ForbiddenHttpException('Access denied');
        }

        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionTeacherindex() {
        if (Yii::$app->user->isGuest || !\Yii::$app->user->identity->is('teacher')) {
            throw new ForbiddenHttpException('Access denied');
        }

        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        // print_r($dataProvider->query);
        $dataProvider->query->andFilterWhere([
            'userLevel' => User::$userLevelOptionsInverted['Student'],
            'creatorId' => \Yii::$app->user->identity->userId
        ]);

        return $this->render('teacherindex', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id) {
	if(Yii::$app->user->isGuest){
	    throw new ForbiddenHttpException('Access denied');
	}
        if (!\Yii::$app->user->identity->is('admin') && !\Yii::$app->user->identity->is('teacher')) {
            throw new ForbiddenHttpException('Access denied');
        }

        $model = $this->findModel($id);

        if (\Yii::$app->user->identity->is('teacher') && $model->userLevel != User::$userLevelOptionsInverted['Student']) {
            throw new ForbiddenHttpException('Access denied');
        }
        if (\Yii::$app->user->identity->is('teacher') && \Yii::$app->user->identity->userId != $model->creatorId) {
            throw new ForbiddenHttpException('Access denied');
        }

        return $this->render('view', [
                    'model' => $model,
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
	if(Yii::$app->user->isGuest){
	    throw new ForbiddenHttpException('Access denied');
	}
        if (!\Yii::$app->user->identity->is('admin') && !\Yii::$app->user->identity->is('teacher')) {
            throw new ForbiddenHttpException('Access denied');
        }

        $model = new User();
        $post = Yii::$app->request->post();
        if ($model->load($post)) {

            // teacher can create students
            if (\Yii::$app->user->identity->is('teacher')) {
                $model->userLevel = User::$userLevelOptionsInverted['Student'];
            }

            $model->creatorId = \Yii::$app->user->identity->userId;

            if ($model->save()) {
                // save new password
                if (isset($post['password']) && $post['password'][0] && $post['password'][0] == $post['password'][1]) {
                    $model->setPassword($post['password'][0]);
                    $model->save();
                }

                return $this->redirect(['view', 'id' => $model->userId]);
            }
        }

        return $this->render('create', [
                    'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id) {
	if(Yii::$app->user->isGuest){
	    throw new ForbiddenHttpException('Access denied');
	}
        if (!\Yii::$app->user->identity->is('admin') && !\Yii::$app->user->identity->is('teacher')) {
            throw new ForbiddenHttpException('Access denied');
        }

        $model = $this->findModel($id);

        // teacher can manage only students
        if (\Yii::$app->user->identity->is('teacher') && $model->userLevel != User::$userLevelOptionsInverted['Student']) {
            throw new ForbiddenHttpException('Access denied');
        }
        if (\Yii::$app->user->identity->is('teacher') && \Yii::$app->user->identity->userId != $model->creatorId) {
            throw new ForbiddenHttpException('Access denied');
        }

        $post = Yii::$app->request->post();
        if ($model->load($post) && $model->save()) {
            // save new password
            if (isset($post['password']) && $post['password'][0]) {

                if ($post['password'][0] == $post['password'][1]) {
                    $model->setPassword($post['password'][0]);
                    $model->save();
                } else {
                    $model->addError('userPassword', $error = 'Type identical passwords, please');
                    return $this->render('update', [
                                'model' => $model,
                    ]);
                }
            }
            return $this->redirect(['view', 'id' => $model->userId]);
        } else {

            $query = new \yii\db\Query;
            $query->from(['disk' => '{{%disk}}'])
                    ->orderBy('disk.diskTitle');
            $disks = $query->all();


            return $this->render('update', [
                        'model' => $model,
                        'disks' => $disks
            ]);
        }
    }

    /**
     * batch user processing
     */
    public function actionBatch() {
	if(Yii::$app->user->isGuest){
	    throw new ForbiddenHttpException('Access denied');
	}
        if (!\Yii::$app->user->identity->is('admin')) {
            throw new ForbiddenHttpException('Access denied');
        }

        $message = '';
        $post = Yii::$app->request->post();
        if (isset($post['csv']) && $post['csv']) {
            $model = new UserBatchForm();

            $model->delimiter = $post['delimiter'];
            $model->enclosure = $post['enclosure'];
            $model->escape = $post['escape'];

            $model->load_csv($post['csv']);

            return $this->render('batch-02-rows', [
                        'message' => $message,
                        'model' => $model
            ]);
        } elseif (isset($post['rows']) && $post['rows']) {
            $model = new UserBatchForm();
            $model->load_rows($post['fields'], $post['rows']);
            // print_r($model);

            $report = $model->executeBatch();
            // print_r($report);exit();
            return $this->render('batch-03-report', [
                        'message' => $message,
                        'report' => $report,
                        'model' => $model
            ]);
        } else {
            $model = new UserBatchForm();
            return $this->render('batch-01-input', [
                        'message' => $message,
                        'model' => $model
            ]);
        }
    }

    public function actionPasswd($key) {

        $message = '';
        $query = User::find();
        $query->andFilterWhere(['userTemporaryKey' => $key]);
        $userModel = $query->one();
        if ($userModel) {
            $model = $userModel;
            $post = Yii::$app->request->post();
            if (isset($post['password']) && $post['password'][0]) {
                if ($post['password'][0] == $post['password'][1]) {
                    $userModel->setPassword($post['password'][0]);
                    $userModel->userTemporaryKey = '';
                    $userModel->save();
                    $model = new User();
                    $message = 'Password updated';

                    $model = new LoginForm();
                    return $this->render('//site/login', [
                                'message' => $message,
                                'model' => $model,
                    ]);
                } else {
                    $message = 'Type identical passwords, please';
                }
            } else {
                $message = '';
            }
        } else {
            $model = new User();
            $message = 'Invalid secure key';
        }

        return $this->render('passwd', [
                    'message' => $message,
                    'model' => $model,
                    'key' => $key
        ]);
    }

    public function actionRecovery() {
        $message = '';
        $post = Yii::$app->request->post();
        if ($post && isset($post['User']) && isset($post['User']['userEMail'])) {

            $query = User::find();
            $query->andFilterWhere([
                'userEMail' => $post['User']['userEMail'],
            ]);
            $userModel = $query->one();
            if ($userModel) {
                // create password recovery link
                $userModel->userTemporaryKey = base64_encode(md5(time() . rand(0, 100001)));
                $userModel->save();

                //$secureUrl = Yii::$app->homeUrl . '?r=user/passwd&key=' . ($userModel->userTemporaryKey);

views/group/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Group */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="group-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'groupName')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'groupDescription')->textarea(['rows' => 6]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/group/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\GroupSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="group-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'groupId') ?>

    <?= $form->field($model, 'groupName') ?>

    <?= $form->field($model, 'groupDescription') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/group/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Group */

$this->title = 'Create Group';

if(\Yii::$app->user->identity->is('admin')){
    $this->params['breadcrumbs'][] = ['label' => 'Groups', 'url' => ['index']];
}elseif(\Yii::$app->user->identity->is('teacher')){
    $this->params['breadcrumbs'][] = ['label' => 'Groups', 'url' => ['teacherindex']];
}

$this->params['breadcrumbs'][] = $this->title;
?>
<div class="group-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/group/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use app\models\User;

/* @var $this yii\web\View */
/* @var $searchModel app\models\GroupSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Groups';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="group-index">

    <h1><?= Html::encode($this->title) ?> <?= Html::a('Create Group', ['create'], ['class' => 'btn btn-success btn-xs']) ?></h1>

<?php Pjax::begin(); ?>    <?php

$columns = [];

$columns[]=['class' => 'yii\grid\ActionColumn'];
$columns[]='groupId';
$columns[]='groupName';
$columns[]='groupDescription:ntext';

// echo "++++++++++++++++";
if (\Yii::$app->user->identity->is('admin')) {
    
        $creatorOptionsQuery = User::find()->where(['or','userLevel='.(User::$userLevelOptionsInverted['Teacher']),'userLevel='.(User::$userLevelOptionsInverted['Admin'])])->all();
        $creatorOptions=[];
        foreach($creatorOptionsQuery as $md){
            $creatorOptions[$md->userId]="{$md->userLastName} {$md->userFirstName}, {$md->userLogin}";
        }
        //        var_dump(join(',',array_keys($creatorOptions)));
        //        echo '<hr>';
        //        var_dump($creatorOptions);
        $columns[] = [
            'attribute' => 'creatorId',
            'label' => 'Creator',
            'filter' => $creatorOptions,
            'content' => function ($model, $key, $index, $column) {
                $creator = $model->creator;
                return $creator ? "{$creator->userLastName} {$creator->userFirstName}, {$creator->userLogin}" : '';
            }
        ];
}

echo GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => $columns,
    ]); ?>
<?php Pjax::end(); ?></div>

views/group/update.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use kartik\widgets\Select2;

/* @var $this yii\web\View */
/* @var $model app\models\Group */

$this->title = 'Update Group: ' . $model->groupName;

if(\Yii::$app->user->identity->is('admin')){
    $this->params['breadcrumbs'][] = ['label' => 'Groups', 'url' => ['index']];
}elseif(\Yii::$app->user->identity->is('teacher')){
    $this->params['breadcrumbs'][] = ['label' => 'Groups', 'url' => ['teacherindex']];
}

$this->params['breadcrumbs'][] = ['label' => $model->groupId, 'url' => ['view', 'id' => $model->groupId]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="group-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    $this->render('_form', [
        'model' => $model,
    ])
    ?>

</div>

<br/><br/>

<h3>Group Members</h3>
<table class='table table-striped table-bordered'>
    <thead>
        <tr>
            <th style="width:10%;"></th>
            <th style="width:90%;">Name</th>
        </tr>
    </thead>
    <tbody id="usercontainer">
    </tbody>
</table>


<h3>Add User</h3>
<div class="row">
    <div class="col-sm-4">Add user:<br/>
        <?php
        // echo '<label class="control-label">Provinces</label>';
        echo Select2::widget([
            'name' => 'newUserId',
            'data' => ArrayHelper::map($students, 'userId', 'userFullName'),
            'options' => [
                'placeholder' => 'Select students ...',
                'multiple' => true,
                'id' => 'newUserId'
            ],
        ]);
        ?>

    </div>
</div>
<br/>
<button id="btnAddUser" class="btn btn-primary"> Add </button>




<br/><br/>
<h3>Disks Access</h3>
<table class='table table-striped table-bordered'>
    <thead>
        <tr>
            <th style="width:10%;"></th>
            <th style="width:50%;">Disk</th>
            <th style="width:20%;">From Date</th>
            <th style="width:20%;">To Date</th>
        </tr>
    </thead>
    <tbody id="container">
    </tbody>
</table>

<h3>Add/Replace Access</h3>
<div class="row">
    <div class="col-sm-4">Disk:<br/>
        <?php echo Html::dropDownList('list', '', ArrayHelper::map($disks, 'diskId', 'diskTitle'), ['class' => 'form-control', 'id' => 'newdiskId']); ?>
    </div>
    <div class="col-sm-2">From Date:<br/><input type="text" id="fromDate" class="form-control"></div>
    <div class="col-sm-2">To Date:<br/><input type="text" id="toDate" class="form-control"></div>
</div>
<br/>
<button id="btnAdd" class="btn btn-primary"> Add / Replace </button>

<?php
$this->registerJsFile( '@web/js/groupaccess.js', ['depends' => [\yii\web\JqueryAsset::className()]] );
$this->registerJsFile( '@web/js/usergroup.js', ['depends' => [\yii\web\JqueryAsset::className()]] );

$this->registerJsFile(
        '@web/js/datepicker/js/bootstrap-datepicker.min.js', ['depends' => [\yii\web\JqueryAsset::className()]]
);

$this->registerJs(
        "   
                window.groupaccess.init({
                    groupId:{$model->groupId},
                    containerId: 'container',
                    btnAdd:'btnAdd'
                });

                jQuery('#fromDate').datepicker({format: 'yyyy-mm-dd'});
                jQuery('#toDate').datepicker({format: 'yyyy-mm-dd'});

                window.usergroup.init({
                    groupId:{$model->groupId},
                    containerId: 'usercontainer',
                    btnAdd:'btnAddUser'
                });

               ", yii\web\View::POS_LOAD, 'my-groupaccess-handler'
);

$this->registerCssFile('@web/js/datepicker/css/bootstrap-datepicker.min.css');

$this->registerCss(
        "   
                .del, .save{ cursor:pointer; margin-right:10px;}
            ");
?>

views/group/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Group */

$this->title = $model->groupName; //.' ('.$model->groupId.')';

if(\Yii::$app->user->identity->is('admin')){
    $this->params['breadcrumbs'][] = ['label' => 'Groups', 'url' => ['index']];
}elseif(\Yii::$app->user->identity->is('teacher')){
    $this->params['breadcrumbs'][] = ['label' => 'Groups', 'url' => ['teacherindex']];
}

$this->params['breadcrumbs'][] = $this->title;
?>
<div class="group-view">

    <h1><?= Html::encode($this->title) ?>
        <?= Html::a('Update', ['update', 'id' => $model->groupId], ['class' => 'btn btn-primary btn-xs']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->groupId], [
            'class' => 'btn btn-danger btn-xs',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </h1>
    <div><?php
    if(\Yii::$app->user->identity->is('admin')){
        $creator = $model->creator;
        if($creator){
            echo "Creator : ". Html::a(" {$creator->userLastName} {$creator->userFirstName}, {$creator->userLogin}", ['/user/view', 'id' => $model->creatorId], ['class' => '']);
        }
    }
    ?></div>
    <div>
        <?=$model->groupDescription?>
    </div>
    
    <h3>Members</h3>
    <div>
        <ol>
        <?php
        foreach($users as $user){
            echo "<li>{$user['userLastName']}, {$user['userFirstName']}, {$user['userLogin']}, {$user['userEMail']}</li>";
        }
        ?>
        </ol>
    </div>

    <h3>Disks</h3>
    <div>
        <ol>
        <?php
        foreach($disks as $disk){
            $fromDate=strtotime($disk['fromDate']);
            $toDate=strtotime($disk['toDate']);

            echo "<li> <span style='color:gray;'>".date(Yii::$app->params['dateformat'],$fromDate)." - ".date(Yii::$app->params['dateformat'],$toDate)."</span>  {$disk['diskTitle']} </li>";
        }
        ?>
        </ol>
    </div>
</div>